version: "3"

services:
  nginx:
    image: nginx:alpine
    tty: true
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "80:80"
    networks:
      - blog-network
    depends_on:
      - node
  node:
    build:
      context: ./
      dockerfile: ./.docker/node/Dockerfile
      args:
        USER: lucasantonio
        GROUP: lucasantonio
    working_dir: /src/app
    tty: true
    expose:
      - "5173"
    volumes:
      - ./:/src/app
    networks:
      - blog-network
    command: >
     sh -c "npm install && npm run dev"

networks:
  blog-network:
    driver: bridge

